version: '3'
services:
  confdaddy-services:
    build: .
    image: confdaddy-services
    container_name: confdaddy-services
    ports:
      - 5000:5000
    volumes:
      - .:/app
    command: /bin/sleep 216000