apiVersion: v1
kind: Service
metadata:
  name: workflow-services-dev
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: workflow-services-dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-services-dev
spec:
  selector:
    matchLabels:
      app: workflow-services-dev
  replicas: 1
  template:
    metadata:
      labels:
        app: workflow-services-dev
    spec:
      containers:
      - name: workflow-services
        image: registry.digitalocean.com/monoxor/workflow-services:dev
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
          - name: DATA_SERVICE_URL
            value: "https://dev.monoxor.com/data-services"
