apiVersion: v1
kind: Service
metadata:
  name: nocode
spec:
  ports:
  - port: 80
    targetPort: 8082
  selector:
    app: nocode
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nocode
spec:
  selector:
    matchLabels:
      app: nocode
  replicas: 2
  template:
    metadata:
      labels:
        app: nocode
    spec:
      containers:
      - name: nocode
        image: registry.digitalocean.com/monoxor/nocode
        ports:
        - containerPort: 8082
