apiVersion: v1
kind: Service
metadata:
  name: proximity-web-dev
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: proximity-web-dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proximity-web-dev
spec:
  selector:
    matchLabels:
      app: proximity-web-dev
  replicas: 1
  template:
    metadata:
      labels:
        app: proximity-web-dev
    spec:
      containers:
      - name: proximity-web-dev
        image: registry.digitalocean.com/monoxor/proximity-web:c301b3c
        ports:
        - containerPort: 80