version: '3'
services:
  tech-conferences:
    build: .
    image: tech-conferences
    container_name: tech-conferences
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    command: /bin/sleep 216000