// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 2XiRTrANos1tumXyUCiwGi
// Component: ujzRZF_qu5
import * as React from "react";

import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_starter_blog.module.css"; // plasmic-import: 2XiRTrANos1tumXyUCiwGi/projectcss
import * as sty from "./PlasmicNewComponent.module.css"; // plasmic-import: ujzRZF_qu5/css

export type PlasmicNewComponent__VariantMembers = {};

export type PlasmicNewComponent__VariantsArgs = {};
type VariantPropType = keyof PlasmicNewComponent__VariantsArgs;
export const PlasmicNewComponent__VariantProps = new Array<VariantPropType>();

export type PlasmicNewComponent__ArgsType = {};
type ArgPropType = keyof PlasmicNewComponent__ArgsType;
export const PlasmicNewComponent__ArgProps = new Array<ArgPropType>();

export type PlasmicNewComponent__OverridesType = {
  root?: p.Flex<"div">;
  box?: p.Flex<"div">;
};

export interface DefaultNewComponentProps {
  className?: string;
}

function PlasmicNewComponent__RenderFunc(props: {
  variants: PlasmicNewComponent__VariantsArgs;
  args: PlasmicNewComponent__ArgsType;
  overrides: PlasmicNewComponent__OverridesType;
  dataFetches?: PlasmicNewComponent__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <div
        data-plasmic-name={"box"}
        data-plasmic-override={overrides.box}
        className={classNames(defaultcss.all, defaultcss.__wab_text, sty.box)}
      >
        {"Enter some text"}
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "box"],
  box: ["box"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  box: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicNewComponent__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicNewComponent__VariantsArgs;
    args?: PlasmicNewComponent__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicNewComponent__Fetches;
  } & Omit<PlasmicNewComponent__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicNewComponent__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicNewComponent__ArgProps,
      internalVariantPropNames: PlasmicNewComponent__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicNewComponent__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicNewComponent";
  } else {
    func.displayName = `PlasmicNewComponent.${nodeName}`;
  }
  return func;
}

export const PlasmicNewComponent = Object.assign(
  // Top-level PlasmicNewComponent renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    box: makeNodeComponent("box"),

    // Metadata about props expected for PlasmicNewComponent
    internalVariantProps: PlasmicNewComponent__VariantProps,
    internalArgProps: PlasmicNewComponent__ArgProps
  }
);

export default PlasmicNewComponent;
/* prettier-ignore-end */
